# Generated by Django 5.0.7 on 2024-08-08 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0002_rename_class_classroom'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Period',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('start_time', models.TimeField()),
                ('end_date', models.TimeField()),
                ('day_of_week', models.CharField(max_length=30)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='classroom.classroom')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class', to='course.course')),
            ],
        ),
    ]
